### PR TITLE
Expose transition

### PR DESCRIPTION
**Pull request by dannymidnight**
This exposes the css transition used in off-canvas for re-use elsewhere.

### CODE REVIEW

**Comment by andrewk** [comment]
I propose defining the animation settings as implemented in asimov-mediabox: https://github.com/99designs/asimov-mediabox/blob/master/_settings.scss#L3

**Comment by xzyfer** [comment]
I can see how breaking it up into `in` and `out` makes sense. In this case we just do

```
"off-canvas": (
  "transitions": (
    "in": transform 0.33s cubic-bezier(0.694, 0.0482, 0.335, 1),
    "out": "off-canvas/transitions/in",
  ),  
)
```

I even see an argument for naming the transitions. Not particularly useful here but as a convention I believe it has legs

```scss
"off-canvas": (
  "transitions": (
    "default": (
      "in": transform 0.33s cubic-bezier(0.694, 0.0482, 0.335, 1),
      "out": "off-canvas/transitions/in",
    ),
  ),  
)
```

However I'm not sure if there is benefit into breaking the transition it's parts. Maybe if you want alter the timing or easing, but we could do that with a new named transition with I think better is for maintaining consistency.

Thoughts @andrewk ?

**Comment by xzyfer** [comment]
I actually think being able to change parts of an animation could be an anti-pattern.

**Comment by andrewk** [comment]
@xzyfer my reasoning for splitting the animation shorthand into its two key components -- the transition bezier and the timing -- is that the property being animated isn't necessary for UI consistency, but the other two values are. If there were a non-broken form of that shorthand whereby the property (eg: `transform`) could be excluded but the other two parts retained, I would prefer that.

IMO any `in`/`out` or other naming is practically moot if the property to be animated is hard-coded in a shorthand format. In mediabox, the "in" and "out" were formerly used for multiple different properties, but then semantics remained the same -- the "in" animation was for a mediabox attaining focus, and the "out" was for losing focus. I didn't mean to suggest that the naming pattern be adopted, but that the granularity of not putting a shorthand CSS property in a component setting be adopted.

**Comment by andrewk** [comment]
> I actually think being able to change parts of an animation could be an anti-pattern.

Disagree.
Using the same animation for simultaneous animations is essential or it looks like crap. Real example: the mediabox had a text colour animation that was triggered by the same interaction as a box-shadow animation. If these were not synced by using the same bezier and timing, they look crap. What I'm suggesting was extracted from a real example in production (which has since been redesigned lolol); as such I strongly disagree with a point like "could be an anti-pattern".

**Comment by dannymidnight** [comment]
All great points. 

> I actually think being able to change parts of an animation could be an anti-pattern.

Yeah I agree with @andrewk, I like the idea of breaking up the animation timing and duration into their own settings without restricting a consumer to use the same transition property. I can see why how it _could_ be an anti-pattern if everyone started overriding timing and durations all over the place but we can uniform this by moving some of the base transitions into more platform wide settings.

e.g.
```scss
"off-canvas": (
  "transitions": (
    "in": (
      "timing": "transitions/timing/bounce-in"
      "duration": "transitions/timing/fast"
    )
  )
)
````

**Comment by xzyfer** [comment]
My argument that is it encourages mix and matching different animation peices i.e. creating bespoke timings.

IMO if you want to tweak the timing for an animation it makes more sense to duplicate that animation in the settings files under a different name. Doing so communicates the intent of the change, as well as isolates all the different animations in one place (the settings file) as opposed to scattering changes throughout components and mixins.

```scss
"off-canvas": (
  "transitions": (
    "fast-bounce": transform 0.33s cubic-bezier(0.694, 0.0482, 0.335, 1),
    "slow-bounce": transform 1s cubic-bezier(0.694, 0.0482, 0.335, 1),
    )
  )
)

// component
.fast {
  transition: get("off-canvas/transitions/fast-bounce");
}
.slow {
  transition: get("off-canvas/transitions/fast-bounce")
}
.foo {
  transition: get("off-canvas/transitions/fast-bounce");
  transition-duration: 0.5s
}
```
VS
```scss
// settings
"off-canvas": (
  "transitions": (
    "fast-bounce": (
      "timing": cubic-bezier(0.694, 0.0482, 0.335, 1)
      "duration": 0.33s
    ),
    "slow-bounce": (
      "timing": cubic-bezier(0.694, 0.0482, 0.335, 1)
      "duration": 1
    )
  )
)

// component
.fast {
  transition: transform get("off-canvas/transitions/fast-bounce/duration") get("off-canvas/transitions/fast-bounce/timing");
}
.slow {
  transition: transform get("off-canvas/transitions/slow-bounce/duration") get("off-canvas/transitions/slow-bounce/timing");
}
.foo {
  transition: transform 0.5s get("off-canvas/transitions/slow-bounce/timing");
}
```

IMO the spoke `.foo` in the first example not only stands out more, it's something that's lintable when we do that. In the latter example the custom duration is less obvious, and lowers visibility of it's existence. This is the anti-pattern I was referring too.

**Comment by dannymidnight** [comment]
> If there were a non-broken form of that shorthand whereby the property (eg: transform) could be excluded but the other two parts retained, I would prefer that.

Alight @andrewk, just had a chat with @xzyfer and we're proposing excluding the `transform-property` setting from the settings map and explicitly defining that part of a transition in your component.

e.g.

```scss
// Settings
"off-canvas": (
  "transitions": (
    "fast-bounce": 0.33s cubic-bezier(0.694, 0.0482, 0.335, 1)
  )
)

// Component
.something {
  transition: transform get('off-canvas/transitions/fast-bouce');
}
```

Based on the [transition-property](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-property) docs, this method also allows transitions to work without defining a `transition-property` as `all` ends up being it's default value. 

e.g.
```
.something {
  transition: get('off-canvas/transitions/fast-bouce');
}
```

**Pull request merged**
