### PR TITLE
Remove custom font smoothing

### PR DESCRIPTION
**Pull request by joshamos**
image

Custom font-smoothing setting is causing jaggy text in Safari 7 & 8 on non-retina monitors. I think it was originally added due to the 3d transforms which have since been removed. Tested in Chrome and Safari and noticed no difference (except for fixing the jaggy text in Safari).

Removing unless objections.

@xzyfer @dennisroethig @alekswitko

### CODE REVIEW

**Comment by dennisroethig** [comment]
If design is happy with that, I'm too! :+1:

**Comment by xzyfer** [comment]
:+1:

Given the breadth of this selector there may be run on affects on other components that's worth keeping an eye out for.

**Comment by alekswitko** [comment]
Is there a crips screenshot I can see of the text?

**Comment by joshamos** [comment]
@alekswitko after:

image

**Pull request merged**
